language: node_js
node_js:
- '5.12'
jobs:
  include:
    - stage: Deploy QA
      script: npm run examples
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: myradar-qa
        acl: public_read
        on:
          repo: thoughtworks/build-your-own-radar
    - stage: Invalidate CDN
      install: pip install --user awscli && export PATH=$PATH:$HOME/.local/bin
      script: 'aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"'